# Generated by Django 5.2.1 on 2025-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathquestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='Easy', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='school_year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='topic',
            field=models.CharField(choices=[('ALGEBRA', 'Algebra'), ('GEOMETRY', 'Geometry'), ('CALCULUS', 'Calculus'), ('STATISTICS', 'Statistics'), ('TRIGONOMETRY', 'Trigonometry'), ('ARITHMETIC', 'Arithmetic')], default='Complex', max_length=20),
            preserve_default=False,
        ),
    ]
