# Generated by Django 5.2.1 on 2025-05-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_mathquestion_difficulty_mathquestion_school_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='question_sets',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.questionset'),
        ),
    ]
